export default {
    rpc: "RPC",
    callback: "Callback",
    ui: "UI",
    logger: "Logger",
    anim: "Animation",
    blip: "Blips",
    camera: "Camera",
    peds: "Peds",
    objects: "Objects",
    marker: "Marker",
    interaction: "Interaction",
    zones: "Zones",
    keybinds: "Keybinds",
    raycast: "Raycast",
    cron: "Cron",
    grid: "Grid",
    table: "Table",
    math: "Math",
    "wait-for": "WaitFor",
    require: "Require",
    streaming: "Streaming Requests",
    proximity: "Proximity",
    dui: "DUI",
};
